services:
  java_app:
    container_name: java_app
    image: bovintech-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/bovintech
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=Pfdk_09.26
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bovintech
      MYSQL_ROOT_PASSWORD: Pfdk_09.26
