spring:
  datasource:
    url: "${MYSQL_URL}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
server:
  port: 8080


