spring:
  datasource:
    url: jdbc:mysql://localhost:3306/certification_hub
    username: root
    password: Pfdk_09.26
  jpa:
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: dev
server:
  port: 8080


